name: zenx_chatbot
description: AI Assistant (ChatBot, Image Generator & Language Translator) by ZenX.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# App version.
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

# Dependencies.
dependencies:
  flutter:
    sdk: flutter

  # IOS Icons.
  cupertino_icons: ^1.0.2
  # Change App Icons.
  icons_launcher: ^2.1.5
  google_fonts: ^6.1.0
  # Lottie Animation.
  lottie: ^2.7.0
  # Hive Database Local Storage.
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  # Accessing Storage Path.
  path_provider: ^2.1.0
  # Custom Animate.
  flutter_animate: ^4.3.0
  # API Call.
  http: ^1.1.0
  # State Management.
  get: ^4.6.6
  flutter_bloc: ^8.1.3
  # Compare Objects.
  equatable: ^2.0.5
  # Text Animations.
  animated_text_kit: ^4.2.2
  # AI Image Generation.
  dart_openai: ^5.0.0
  # Cache Image.
  cached_network_image: ^3.3.0
  # Save Image To Gallery.
  gallery_saver_updated: ^3.0.0
  # Share Image
  share_plus: ^7.2.1
  # FAB Button
  flutter_speed_dial: ^7.0.0
  # Storage Chat Bot Messages.
  realm: ^1.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Dart Effective.
  flutter_lints: ^2.0.0


flutter:
  # Enable Material Design.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/
    - assets/lottie/
    - assets/icon/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
